# Generated by Django 5.2 on 2025-04-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_passport_no_userprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="passport_no",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
