# Generated by Django 5.2 on 2025-04-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_tourpackage_booking_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourpackage",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
