# Generated by Django 5.2 on 2025-04-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_tourpackage_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="users.tourpackage",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("qr", "QR Code"),
                    ("credit", "Credit Card"),
                    ("bank", "Bank Transfer"),
                ],
                max_length=50,
            ),
        ),
    ]
