# Generated by Django 5.2 on 2025-05-15 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_booking_note_alter_booking_package_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourPackageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="packages/gallery/")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="users.tourpackage",
                    ),
                ),
            ],
        ),
    ]
