# Generated by Django 5.2 on 2025-05-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_tourpackageimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="slip_image",
            field=models.ImageField(blank=True, null=True, upload_to="payment_slips/"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("qr", "QR Code"),
                    ("credit", "Credit Card"),
                    ("bank", "Bank Transfer"),
                    ("slip", "Bank Slip"),
                ],
                max_length=50,
            ),
        ),
    ]
