# Generated by Django 5.2 on 2025-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_payment_is_verified_payment_slip_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourpackage",
            name="activities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="duration_detail",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="excludes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="group_size",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="includes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="languages",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="meeting_point",
            field=models.TextField(blank=True),
        ),
    ]
