# Generated by Django 5.2.5 on 2025-08-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_tourpackage_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
    ]
