# Generated by Django 5.2.5 on 2025-08-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userprofile_is_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/'),
        ),
    ]
