# Generated by Django 5.2.14 on 2026-05-18 05:26

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_tourpackage_map_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.get_file_path
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.get_file_path
            ),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="map_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.get_file_path
            ),
        ),
    ]
